// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProvider struct {
	ID        int32
	Email     string
	Provider  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Certificate struct {
	ID          int32
	Reference   uuid.UUID
	UserID      int32
	LanguageID  int32
	SeriesID    int32
	CompletedAt pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type CommentReply struct {
	ID        int32
	AuthorID  int32
	CommentID int32
	Reply     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Donation struct {
	ID           int32
	UserID       int32
	Amount       int64
	Currency     string
	Recurring    bool
	RecurringRef pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Language struct {
	ID        int32
	Name      string
	Slug      string
	Icon      string
	AuthorID  int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Lecture struct {
	ID               int32
	Title            string
	Position         int16
	IsPublished      bool
	CommentsCount    int32
	WatchTimeSeconds int32
	ReadTimeSeconds  int32
	AuthorID         int32
	LanguageSlug     string
	SeriesSlug       string
	SeriesPartID     int32
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type LectureArticle struct {
	ID              int32
	LectureID       int32
	ReadTimeSeconds int32
	Content         string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type LectureComment struct {
	ID           int32
	AuthorID     int32
	LectureID    int32
	Comment      string
	RepliesCount int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type LectureFile struct {
	ID        int32
	LectureID int32
	AuthorID  int32
	File      uuid.UUID
	Ext       string
	Filename  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type LectureProgress struct {
	ID                   int32
	UserID               int32
	LanguageID           int32
	LectureID            int32
	SeriesProgressID     int32
	SeriesPartProgressID int32
	IsCompleted          bool
	CompletedAt          pgtype.Timestamp
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
}

type LectureVideo struct {
	ID               int32
	LectureID        int32
	Url              string
	WatchTimeSeconds int32
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type Payment struct {
	ID         int32
	PaymentRef string
	UserID     int32
	DonationID int32
	Amount     int64
	Currency   string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Series struct {
	ID               int32
	Title            string
	Slug             string
	Description      string
	PartsCount       int16
	LecturesCount    int16
	WatchTimeSeconds int32
	ReadTimeSeconds  int32
	ReviewAvg        int16
	ReviewCount      int32
	IsPublished      bool
	LanguageSlug     string
	AuthorID         int32
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type SeriesImage struct {
	ID        int32
	SeriesID  int32
	AuthorID  int32
	File      uuid.UUID
	Ext       string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type SeriesPart struct {
	ID               int32
	Title            string
	LanguageSlug     string
	SeriesSlug       string
	Description      string
	Position         int16
	LecturesCount    int16
	WatchTimeSeconds int32
	ReadTimeSeconds  int32
	IsPublished      bool
	AuthorID         int32
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type SeriesPartProgress struct {
	ID               int32
	UserID           int32
	SeriesPartID     int32
	LanguageID       int32
	SeriesProgressID int32
	LecturesCount    int16
	IsCompleted      bool
	CompletedAt      pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type SeriesProgress struct {
	ID            int32
	UserID        int32
	SeriesID      int32
	LanguageID    int32
	LecturesCount int16
	PartsCount    int16
	IsCompleted   bool
	CompletedAt   pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type SeriesReview struct {
	ID         int32
	AuthorID   int32
	SeriesID   int32
	LanguageID int32
	Rating     int16
	Review     pgtype.Text
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type SeriesTag struct {
	SeriesID  int32
	TagID     int32
	CreatedAt pgtype.Timestamp
}

type Tag struct {
	ID        int32
	Name      string
	AuthorID  int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID          int32
	FirstName   string
	LastName    string
	Location    string
	Email       string
	BirthDate   pgtype.Date
	Version     int16
	IsAdmin     bool
	IsStaff     bool
	IsConfirmed bool
	Password    pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
