// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: series_progress.sql

package db

import (
	"context"
)

const countSeriesProgressBySeriesSlug = `-- name: CountSeriesProgressBySeriesSlug :one
SELECT COUNT("id") FROM "series_progress"
WHERE "series_slug" = $1
LIMIT 1
`

func (q *Queries) CountSeriesProgressBySeriesSlug(ctx context.Context, seriesSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, countSeriesProgressBySeriesSlug, seriesSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSeriesProgress = `-- name: CreateSeriesProgress :one

INSERT INTO "series_progress" (
  "language_slug",
  "series_slug",
  "language_progress_id",
  "user_id"
) VALUES (
  $1,
  $2,
  $3,
  $4
) RETURNING id, user_id, series_slug, language_slug, language_progress_id, completed_sections, completed_lessons, parts_count, completed_at, viewed_at, created_at, updated_at
`

type CreateSeriesProgressParams struct {
	LanguageSlug       string
	SeriesSlug         string
	LanguageProgressID int32
	UserID             int32
}

// Copyright (C) 2024 Afonso Barracha
//
// This file is part of KiwiScript.
//
// KiwiScript is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// KiwiScript is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with KiwiScript.  If not, see <https://www.gnu.org/licenses/>.
func (q *Queries) CreateSeriesProgress(ctx context.Context, arg CreateSeriesProgressParams) (SeriesProgress, error) {
	row := q.db.QueryRow(ctx, createSeriesProgress,
		arg.LanguageSlug,
		arg.SeriesSlug,
		arg.LanguageProgressID,
		arg.UserID,
	)
	var i SeriesProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeriesSlug,
		&i.LanguageSlug,
		&i.LanguageProgressID,
		&i.CompletedSections,
		&i.CompletedLessons,
		&i.PartsCount,
		&i.CompletedAt,
		&i.ViewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementSeriesProgressCompletedLessons = `-- name: DecrementSeriesProgressCompletedLessons :exec
UPDATE "series_progress" SET
  "completed_lessons" = "completed_lessons" - 1
WHERE "id" = $1
`

func (q *Queries) DecrementSeriesProgressCompletedLessons(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, decrementSeriesProgressCompletedLessons, id)
	return err
}

const decrementSeriesProgressCompletedSections = `-- name: DecrementSeriesProgressCompletedSections :exec
UPDATE "series_progress" SET
  "completed_sections" = "completed_sections" - 1,
  "completed_lessons" = "completed_lessons" - $1
WHERE "id" = $2
`

type DecrementSeriesProgressCompletedSectionsParams struct {
	CompletedLessons int16
	ID               int32
}

func (q *Queries) DecrementSeriesProgressCompletedSections(ctx context.Context, arg DecrementSeriesProgressCompletedSectionsParams) error {
	_, err := q.db.Exec(ctx, decrementSeriesProgressCompletedSections, arg.CompletedLessons, arg.ID)
	return err
}

const deleteSeriesProgress = `-- name: DeleteSeriesProgress :exec
DELETE FROM "series_progress"
WHERE "id" = $1
`

func (q *Queries) DeleteSeriesProgress(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSeriesProgress, id)
	return err
}

const findSeriesProgressByLanguageProgressID = `-- name: FindSeriesProgressByLanguageProgressID :many
SELECT id, user_id, series_slug, language_slug, language_progress_id, completed_sections, completed_lessons, parts_count, completed_at, viewed_at, created_at, updated_at FROM "series_progress"
WHERE "language_progress_id" = $1
ORDER BY "viewed_at" DESC
`

func (q *Queries) FindSeriesProgressByLanguageProgressID(ctx context.Context, languageProgressID int32) ([]SeriesProgress, error) {
	rows, err := q.db.Query(ctx, findSeriesProgressByLanguageProgressID, languageProgressID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SeriesProgress{}
	for rows.Next() {
		var i SeriesProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SeriesSlug,
			&i.LanguageSlug,
			&i.LanguageProgressID,
			&i.CompletedSections,
			&i.CompletedLessons,
			&i.PartsCount,
			&i.CompletedAt,
			&i.ViewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSeriesProgressBySlugAndUserID = `-- name: FindSeriesProgressBySlugAndUserID :one
SELECT id, user_id, series_slug, language_slug, language_progress_id, completed_sections, completed_lessons, parts_count, completed_at, viewed_at, created_at, updated_at FROM "series_progress"
WHERE
    "language_slug" = $1 AND
    "series_slug" = $2 AND
    "user_id" = $3
LIMIT 1
`

type FindSeriesProgressBySlugAndUserIDParams struct {
	LanguageSlug string
	SeriesSlug   string
	UserID       int32
}

func (q *Queries) FindSeriesProgressBySlugAndUserID(ctx context.Context, arg FindSeriesProgressBySlugAndUserIDParams) (SeriesProgress, error) {
	row := q.db.QueryRow(ctx, findSeriesProgressBySlugAndUserID, arg.LanguageSlug, arg.SeriesSlug, arg.UserID)
	var i SeriesProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeriesSlug,
		&i.LanguageSlug,
		&i.LanguageProgressID,
		&i.CompletedSections,
		&i.CompletedLessons,
		&i.PartsCount,
		&i.CompletedAt,
		&i.ViewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementSeriesProgressCompletedLessons = `-- name: IncrementSeriesProgressCompletedLessons :exec
UPDATE "series_progress" SET
  "completed_lessons" = "completed_lessons" + 1
WHERE "id" = $1
`

func (q *Queries) IncrementSeriesProgressCompletedLessons(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementSeriesProgressCompletedLessons, id)
	return err
}

const incrementSeriesProgressCompletedSections = `-- name: IncrementSeriesProgressCompletedSections :one
UPDATE "series_progress" SET
    "completed_sections" = "series_progress"."completed_sections" + 1,
    "completed_lessons" = "series_progress"."completed_lessons" + 1,
    "completed_at" = CASE
        WHEN (
            "series"."sections_count" + 1 > "series_progress"."completed_sections" AND
            "series_progress"."completed_at" IS NULL
        ) THEN (NOW())
        ELSE "series_progress"."completed_at"
    END
FROM "series"
WHERE "series_progress"."id" = $1
RETURNING series_progress.id, series_progress.user_id, series_progress.series_slug, series_progress.language_slug, series_progress.language_progress_id, series_progress.completed_sections, series_progress.completed_lessons, series_progress.parts_count, series_progress.completed_at, series_progress.viewed_at, series_progress.created_at, series_progress.updated_at
`

func (q *Queries) IncrementSeriesProgressCompletedSections(ctx context.Context, id int32) (SeriesProgress, error) {
	row := q.db.QueryRow(ctx, incrementSeriesProgressCompletedSections, id)
	var i SeriesProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeriesSlug,
		&i.LanguageSlug,
		&i.LanguageProgressID,
		&i.CompletedSections,
		&i.CompletedLessons,
		&i.PartsCount,
		&i.CompletedAt,
		&i.ViewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeSeriesProgressCompletedLessons = `-- name: RemoveSeriesProgressCompletedLessons :exec
UPDATE "series_progress" SET
  "completed_lessons" = "completed_lessons" - $1
WHERE "id" = $2
`

type RemoveSeriesProgressCompletedLessonsParams struct {
	CompletedLessons int16
	ID               int32
}

func (q *Queries) RemoveSeriesProgressCompletedLessons(ctx context.Context, arg RemoveSeriesProgressCompletedLessonsParams) error {
	_, err := q.db.Exec(ctx, removeSeriesProgressCompletedLessons, arg.CompletedLessons, arg.ID)
	return err
}

const updateSeriesProgressViewedAt = `-- name: UpdateSeriesProgressViewedAt :exec
UPDATE "series_progress" SET
  "viewed_at" = NOW()
WHERE "id" = $1
`

func (q *Queries) UpdateSeriesProgressViewedAt(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateSeriesProgressViewedAt, id)
	return err
}
