// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: series_pictures.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSeriesPicture = `-- name: CreateSeriesPicture :one

INSERT INTO "series_pictures" (
    "id",
    "series_id",
    "author_id",
    "ext"
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, series_id, author_id, ext, created_at, updated_at
`

type CreateSeriesPictureParams struct {
	ID       uuid.UUID
	SeriesID int32
	AuthorID int32
	Ext      string
}

// Copyright (C) 2024 Afonso Barracha
//
// This file is part of KiwiScript.
//
// KiwiScript is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// KiwiScript is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with KiwiScript.  If not, see <https://www.gnu.org/licenses/>.
func (q *Queries) CreateSeriesPicture(ctx context.Context, arg CreateSeriesPictureParams) (SeriesPicture, error) {
	row := q.db.QueryRow(ctx, createSeriesPicture,
		arg.ID,
		arg.SeriesID,
		arg.AuthorID,
		arg.Ext,
	)
	var i SeriesPicture
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.AuthorID,
		&i.Ext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSeriesPicture = `-- name: DeleteSeriesPicture :exec
DELETE FROM "series_pictures"
WHERE "id" = $1
`

func (q *Queries) DeleteSeriesPicture(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSeriesPicture, id)
	return err
}

const findSeriesPictureBySeriesID = `-- name: FindSeriesPictureBySeriesID :one
SELECT id, series_id, author_id, ext, created_at, updated_at FROM "series_pictures"
WHERE "series_id" = $1
LIMIT 1
`

func (q *Queries) FindSeriesPictureBySeriesID(ctx context.Context, seriesID int32) (SeriesPicture, error) {
	row := q.db.QueryRow(ctx, findSeriesPictureBySeriesID, seriesID)
	var i SeriesPicture
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.AuthorID,
		&i.Ext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
